version: '3'
services:
  lodview:
    build:
      context: ./lodview
      args:
        LODLIVE_URL: http://localhost:8081/app_en.html
        SPARQL_ENDPOINT_URL: http://virtuoso:8890/sparql/
        SPARQL_ENDPOINT_TYPE: virtuoso
        NAMESPACE: http://localhost/ns/
    ports:
      - "8080:8080"
  virtuoso:
    build: ./virtuoso
    volumes:
      - ./data/virtuoso:/data
    ports:
      - "8890:8890"
  lodlive:
    build:
      context: ./lodlive
      args:
        SPARQL_ENDPOINT_URL: http://localhost:8890/sparql/
        NAMESPACE_BASE: http://localhost/ns/
    ports:
      - "8081:80"
