version: '3'
services:
  lodview:
    build:
      context: ./lodview
      args:
        LODLIVE_EXTERNAL_URL: http://localhost/lodlive/app_en.html
        SPARQL_ENDPOINT_EXTERNAL_URL: http://nginx/sparql/
        SPARQL_ENDPOINT_TYPE: virtuoso
        NAMESPACE: http://localhost/ns/
  virtuoso:
    build: ./virtuoso
    volumes:
      - ./data/virtuoso:/data
  lode:
    build: ./lode
  nginx:
    build:
      context: ./nginx
      args:
        EXTERNAL_HOSTNAME: localhost
        NAMESPACE_BASE: http://localhost/ns/
    ports:
      - "80:80"
